### ISSUE TITLE
will you consider adding jasync-sql driver

### ISSUE THREAD

**Issue by oshai** [micronaut-projects/micronaut-sql#3]
This is an async sql driver (uses netty) that can connect both PostgreSQL and MySQL that we maintain: https://github.com/jasync-sql/jasync-sql

Will you consider adding support for it?

**Comment by graemerocher** [comment]
Could definitely be supported with a module similar to https://github.com/micronaut-projects/micronaut-sql/tree/master/postgres-reactive, would you guys be interested in sending a PR?

**Comment by oshai** [comment]
Yes, sending a PR is a good option. Should I basically clone the library and replace the implementation? Are there any things that are redundant?

**Comment by graemerocher** [comment]
That works, I don't know enough about how jasync-sql is configured, but the Postgres implementation used `@ConfigurationBuilder` for example which just delegates the configuration options to the backing library https://github.com/micronaut-projects/micronaut-sql/blob/master/postgres-reactive/src/main/java/io/micronaut/configuration/postgres/reactive/PgPoolConfiguration.java#L32

Some things may be redundant, depends on how much of Micronaut you want to support. The postgres implementation provides a `HealthIndicator` for example so that health checks fail in the data source goes down

**Comment by oshai** [comment]
jasync configuration is using an object called ConnctionPoolConfiguration: https://github.com/jasync-sql/jasync-sql/blob/2ad6e743ba75ae565ad6978522ad7fb4e173a1fc/db-async-common/src/main/java/com/github/jasync/sql/db/ConnectionPoolConfiguration.kt#L52

will adding the annotation allow to configure that object?

**Comment by graemerocher** [comment]
Should do, I'm no Kotlin expert but if Java sees regular Java bean setters from the Kotlin data class it should just work

**Comment by oshai** [comment]
yes, It's the same. I will create an initial PR.

**Comment by oshai** [comment]
I created a PR: https://github.com/micronaut-projects/micronaut-sql/pull/4 let's continue the discussion over there.

**Comment by graemerocher** [comment]
Merged. Thanks for the PR and contribution
